# Generated by Django 4.2.8 on 2026-01-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDESolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation', models.TextField(help_text='The partial differential equation')),
                ('boundary_conditions', models.TextField(blank=True, help_text='Boundary conditions')),
                ('initial_conditions', models.TextField(blank=True, help_text='Initial conditions')),
                ('solution', models.TextField(help_text='The solution to the PDE')),
                ('method_used', models.CharField(help_text='Method used to solve', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDE Solution',
                'verbose_name_plural': 'PDE Solutions',
                'ordering': ['-created_at'],
            },
        ),
    ]
